name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./src/MyProject  # Change directory to where the .csproj is located
      run: dotnet restore
    - name: Build
      working-directory: ./src/MyProject  # Build in the same directory
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./src/MyProject  # Run tests in the same directory
      run: dotnet test --no-build --verbosity normal
